import {
	SESSION_DURATION_DAYS as SESSION_DURATION_DAYS_STR,
	RENEW_SESSION_DAYS as RENEW_SESSION_DAYS_STR,
	VERIFICATION_CODE_ALPHABET
} from '$env/static/private';

const SESSION_DURATION_DAYS = parseInt(SESSION_DURATION_DAYS_STR);

if (isNaN(SESSION_DURATION_DAYS)) {
	throw new Error(`Invalid SESSION_DURATION_DAYS: ${SESSION_DURATION_DAYS}`);
}

const RENEW_SESSION_DAYS = parseInt(RENEW_SESSION_DAYS_STR);

if (isNaN(RENEW_SESSION_DAYS)) {
	throw new Error(`Invalid RENEW_SESSION_DAYS: ${RENEW_SESSION_DAYS}`);
}

export { SESSION_DURATION_DAYS, RENEW_SESSION_DAYS, VERIFICATION_CODE_ALPHABET };
