import {
	SESSION_DURATION_DAYS as SESSION_DURATION_DAYS_STR,
	RENEW_SESSION_DAYS as RENEW_SESSION_DAYS_STR,
	VERIFICATION_CODE_ALPHABET,
	VERIFICATION_CODE_DURATION_MINUTES as VERIFICATION_CODE_DURATION_MINUTES_STR
} from '$env/static/private';

const SESSION_DURATION_DAYS = parseInt(SESSION_DURATION_DAYS_STR);

if (isNaN(SESSION_DURATION_DAYS)) {
	throw new Error(`Invalid SESSION_DURATION_DAYS: ${SESSION_DURATION_DAYS}`);
}

const RENEW_SESSION_DAYS = parseInt(RENEW_SESSION_DAYS_STR);

if (isNaN(RENEW_SESSION_DAYS)) {
	throw new Error(`Invalid RENEW_SESSION_DAYS: ${RENEW_SESSION_DAYS}`);
}

const VERIFICATION_CODE_DURATION_MINUTES = parseInt(VERIFICATION_CODE_DURATION_MINUTES_STR);

if (isNaN(VERIFICATION_CODE_DURATION_MINUTES)) {
	throw new Error(
		`Invalid VERIFICATION_CODE_DURATION_MINUTES: ${VERIFICATION_CODE_DURATION_MINUTES}`
	);
}

export {
	SESSION_DURATION_DAYS,
	RENEW_SESSION_DAYS,
	VERIFICATION_CODE_ALPHABET,
	VERIFICATION_CODE_DURATION_MINUTES
};
