import { encodeBase32LowerCase } from '@oslojs/encoding';

/**
 * Generated by `sv create` as part of the Lucia demo app.
 *
 * @returns
 */
export function generateUniqueId() {
	// ID with 120 bits of entropy, or about the same as UUID v4.
	const bytes = crypto.getRandomValues(new Uint8Array(15));
	const id = encodeBase32LowerCase(bytes);
	return id;
}
